name: dev workflow

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  run-tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  deploy:
    runs-on: ubuntu-latest
    needs: run-tests
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/services/${{ secrets.RENDER_SERVICE_ID }}/deploys --header 'accept: application/json' --header 'content-type: application/json' --header 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}'"
"